name: simplepod
description: A podcast listener app. 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  parsed_readmore: ^0.0.6
  podcast_search: ^0.6.1
  rich_readmore: ^1.0.5
  skeletonizer: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          # weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700