name: simplepod
description: A podcast listener app. 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  html: ^0.15.4
  intl: ^0.18.1
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  parsed_readmore: ^0.0.6
  podcast_search: ^0.6.3
  rich_readmore: ^1.0.5
  skeletonizer: ^0.7.0
  solar_icons: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          # weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
  - assets/images/placeholder.png